import React, { useState, useEffect } from 'react';

const Analytics = () => {
  // We add a 'timestamp' to the image URL to force the browser to bypass its cache
  // and show the newest plot immediately after training.
  const [plotUrl, setPlotUrl] = useState('');
  const [loading, setLoading] = useState(true);

  const refreshPlot = () => {
    setLoading(true);
    // Adding ?t= ensures the browser sees a "new" URL and re-fetches the image
    const newUrl = `http://localhost:8000/analytics/plot?t=${new Date().getTime()}`;
    setPlotUrl(newUrl);
  };

  useEffect(() => {
    // Initial load of the plot
    refreshPlot();
  }, []);

  return (
    <div className="p-10 space-y-10 text-white animate-in fade-in duration-700">
      <header className="flex justify-between items-center">
        <div>
          <h1 className="text-4xl font-black">System Analytics</h1>
          <p className="text-slate-500 mt-2">Real-time performance metrics for GesturePro AI</p>
        </div>
        <button 
          onClick={refreshPlot}
          className="bg-indigo-600 hover:bg-indigo-500 px-6 py-2 rounded-full font-bold transition-all shadow-lg active:scale-95"
        >
          🔄 Refresh Analytics
        </button>
      </header>

      {/* Stats Summary Grid (Visual Indicators) */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-[#161b22] p-8 rounded-[2rem] border border-slate-800 shadow-xl">
          <p className="text-slate-500 text-sm font-bold uppercase tracking-widest">Model Status</p>
          <h3 className="text-2xl font-bold mt-2 text-green-400">Ready & Active</h3>
        </div>
        <div className="bg-[#161b22] p-8 rounded-[2rem] border border-slate-800 shadow-xl">
          <p className="text-slate-500 text-sm font-bold uppercase tracking-widest">Device Input</p>
          <h3 className="text-2xl font-bold mt-2">Webcam Core</h3>
        </div>
        <div className="bg-[#161b22] p-8 rounded-[2rem] border border-slate-800 shadow-xl">
          <p className="text-slate-500 text-sm font-bold uppercase tracking-widest">AI Engine</p>
          <h3 className="text-2xl font-bold mt-2">TensorFlow 2.x</h3>
        </div>
      </div>

      {/* Accuracy and Loss Chart Section */}
      <div className="bg-[#161b22] p-10 rounded-[3rem] border border-slate-800 shadow-2xl">
        <div className="flex justify-between items-center mb-8">
          <h2 className="text-xl font-bold">Training Accuracy & Loss Curves</h2>
          <span className="text-xs bg-slate-800 text-slate-400 px-3 py-1 rounded-full uppercase tracking-tighter">
            Auto-Generated by training.py
          </span>
        </div>

        <div className="min-h-[400px] flex items-center justify-center bg-[#0d1117] rounded-3xl overflow-hidden border border-slate-800">
          {plotUrl ? (
            <img 
              src={plotUrl} 
              alt="Model Training Analytics" 
              className="w-full h-auto object-contain p-4"
              onLoad={() => setLoading(false)}
              onError={(e) => {
                e.target.style.display = 'none';
                setLoading(true);
              }}
            />
          ) : null}

          {loading && (
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500 mx-auto mb-4"></div>
              <p className="text-slate-500 font-medium">No training plot found. Go to Trainer to generate data.</p>
            </div>
          )}
        </div>
        
        <p className="text-slate-600 text-sm mt-6 text-center italic">
          Tip: Look for the **Accuracy** line to go up and the **Loss** line to go down. This confirms your AI is learning your custom gestures.
        </p>
      </div>
    </div>
  );
};

export default Analytics;